verbal/urls.py
from django.contrib import admin
from django.urls import path
import flash.views as f

urlpatterns = [
    path('', f.welcome, name = 'welcome'),
    path('<int:topic_id>/', f.home_view, name = 'topic-page'),
    path('loading/', f.redirect_view, name = 'loading'),
    path('create-topic/', f.create_topic, name='create-topic'),
    path('create-topic/<str:tag>/', f.create_topic, name='create-topic-for-tag'),
    path('edit-topic', f.edit_topic, name='edit-topic'),
    path('delete-topic/', f.delete_topic, name='delete-topic'),
    path('create-tag/', f.create_tag, name='create-tag'),
    path('remove-tag/', f.remove_tag, name='remove-tag'),
    path('topic/<int:topic_id>/add_use_case/', f.add_use_case, name='add_use_case'),
    path('edit-use-case/', f.edit_use_case, name='edit-use-case'),
    path('delete-use-case/', f.delete_use_case, name='delete-use-case'),
    path('topic/<int:topic_id>/add_comparison/', f.add_comparison, name='add_comparison'),
    path('comparison/<int:comparison_id>/comparison-rows/', f.comparison_datatable, name='comparisons-data'),
    path('comparison/<int:comparison_id>/edit-comparison/', f.edit_comparison, name='edit-comparison'),
    path('delete-comp/', f.delete_comparison, name='delete-comparison'),
    path('admin/', admin.site.urls),
]

flash/models.py
from django.db import models

class Topic(models.Model):
    topic = models.CharField(max_length=200, null=False, blank=False)
    description = models.TextField(max_length=400, null=True, blank=True)

    def serialize(self):
        return {
            'id': self.id,
            'topic': self.topic,
            'description': self.description,
        }

class UseCase(models.Model):
    topic = models.ForeignKey(Topic, related_name='use_cases', on_delete=models.CASCADE)
    description = models.TextField()

class Comparison(models.Model):
    topic = models.ForeignKey(Topic, related_name='comparisons', on_delete=models.CASCADE)
    comparison1 = models.CharField(max_length=255, null=True, blank=True)
    comparison2 = models.CharField(max_length=255, null=True, blank=True)
    
class ComparisonRow(models.Model):
    comparison = models.ForeignKey(Comparison, related_name='comparison_rows', on_delete=models.CASCADE)
    keyword = models.CharField(max_length=200)
    row1 = models.TextField()
    row2 = models.TextField()
    
class Tag(models.Model):
    topic = models.ManyToManyField(Topic)
    tag = models.CharField(max_length=200)

class Note(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='notes')
    content = models.TextField()

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% block stylesheet %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/flashcard.css' %}">
    {% endblock %}

    <title>Verbal!</title>
  </head>
  <body>
    <div class="container">
      <div id="message-container"></div>
      {% block content %}
        {% if topic_id is not None %}
          <a href="{{topic_id}}" class="btn btn-primary btn-lg" role="button">Go To Topics</a>
        {% else %}
          <h1> Create your first Topic! </h1>
          <a href="/create-topic" class="btn btn-primary btn-lg" role="button"> + </a>
        {% endif %}
      {% endblock %}
  </div>


<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

<!-- Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

<!-- Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

<!-- DataTables CSS -->
<link rel="stylesheet" href="https://cdn.datatables.net/2.0.6/css/dataTables.bootstrap5.css">

<!-- DataTables JS -->
<script src="https://cdn.datatables.net/2.0.6/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.0.6/js/dataTables.bootstrap5.js"></script>

<!-- Bootstrap Icons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

  <!-- Optional JavaScript -->
  {% block javascript %}
    <script src="{% static 'js/flashcard-form.js' %}"></script>
  {% endblock %}
  </body>
</html>

<script>
  var createTagUrl = "{% url 'create-tag' %}";
  var removeTagUrl = "{% url 'remove-tag' %}";
  var editTopicUrl = "{% url 'edit-topic' %}";
  var deleteTopicUrl = "{% url 'delete-topic' %}";
  var editUseCaseUrl = "{% url 'edit-use-case' %}";
  var deleteUseCaseUrl = "{% url 'delete-use-case' %}";
</script>

templates/create_tag.html
{% extends 'base.html' %}
{% block content %}

     <form method="post">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit" class="btn btn-primary" name = 'submit'> Submit </button>
     </form>

{% endblock %}

templates/create_topic.html
{% extends 'base.html' %}
{% block content %}

     <form method="post">
          <input type="hidden" id="topic" value="{{topic}}">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit" class="btn btn-primary" name = 'submit'> Submit </button>
     </form>

     <script>
          document.querySelector('form').classList.add('submit-form')
     </script>

{% endblock %}

templates/create_word.html
{% extends 'base.html' %}
{% block content %}

     <form method="post">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit" class="btn btn-primary" name = 'submit'> Submit </button>
     </form>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<button type="button" class="btn btn-secondary">
  <a href="/create-topic" style="color: white">Add new topic</a>
</button>
<a href="/1" id="welcome" style="display:none" role="button">Go Back</a>
<input type="hidden" name= 'id' value = {{id}} >

<div class="row p-5">
  <div class="col-1">
    {% if id != 1 %}
      <form method="get" action="{% url 'loading' %}">
        <button class="btn" name='prev' value={{id}}>
          {% csrf_token %}
          <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-left-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
            <path fill-rule="evenodd" d="M8.354 11.354a.5.5 0 0 0 0-.708L5.707 8l2.647-2.646a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708 0z"/>
            <path fill-rule="evenodd" d="M11.5 8a.5.5 0 0 0-.5-.5H6a.5.5 0 0 0 0 1h5a.5.5 0 0 0 .5-.5z"/>
          </svg>
        </button>
      </form>
    {% endif %}
  </div>
  <div class="col">
    <h1 class="editable" id = 'card-topic'> 
      <span> {{topic}} </span> 
      <div>
        <button class="btn btn-outline-danger bi-trash3-fill delete-topic" title="Delete this Topic"></button>
        <button class="btn btn-outline-success bi-pencil-fill edit" title="Edit Title" data-toggle="modal" data-target="#editTopic"></button>
      </div>
    </h1>
  </div>
  <div class="col-1">
    <form method="get" action="{% url 'loading' %}">
      <button class="btn" name='next' value={{id}}>
        {% csrf_token %}
        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-right-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
          <path fill-rule="evenodd" d="M7.646 11.354a.5.5 0 0 1 0-.708L10.293 8 7.646 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0z"/>
          <path fill-rule="evenodd" d="M4.5 8a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5z"/>
        </svg>
      </button>
    </form>
  </div>
</div>

<!-- Description -->
<div class = "taggable editable" id = 'card-description'> 
  <span> {{description}}  </span>
  <div class="pull-right">
    <button class="btn btn-outline-success bi-pencil-fill edit" title="Edit Description" data-toggle="modal" data-target="#editTopic" ></button>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="editTopic" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
        </div>
        <div class="modal-body">
              <form method="post" id="topic-form">
              {% csrf_token %}
              <input type="hidden" name="id" value="{{ id }}">
              <div class="form-group" name="card-topic" style="display:none">
                  <label for="id_topic"><b> Topic: </b></label>
                  <input name="topic" id="id_topic" type="text" value={{topic}} maxlength="200" class="form-control">
              </div>
              <div class="form-group" name="card-description" style="display:none">
                  <label for="id_description"><b> Description: </b></label>
                  <textarea name="description" id="id_description" cols="40" rows="10" maxlength="400" class="form-control">{{description}}</textarea>
                </div>
              <button class="btn btn-info mt-3 topic-edit-submit">Save changes</button>
              </form>
        </div>
    </div>
  </div>
</div>

<!-- Use Case -->
{% if use_cases is not None%}
  {% include 'use_case/use_cases.html'  %}
{% endif %}
<a href="{% url 'add_use_case' topic_id=id %}" class="pull-right">Add Use Case</a>
<br>
<!-- Comparisons -->
{% if comparisons is not None%}
  {% include 'comparisons/comparisons.html'  %}
{% endif %}
<a href="{% url 'add_comparison' topic_id=id %}" class="pull-right">Add a Comparison</a>


<!-- tags -->
<div id="all-tags" style="display:none">{{tags}}</div>
<div id="is-topic" style="display:none">{{is_topic}}</div>
<div class="tag-button-grp" style="display:none">
  <div style="background-color:white;padding:5px;border-radius:0.75rem">
    <a class="btn btn-info bi-arrow-up-right tag-to-topic" title="Create Topic from Tag"></a>
    <button type = "button" class="btn btn-danger bi-x-square remove-tag" title="Delete Tag"></button>
  </div>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/flashcard-show.js' %}"></script>
<script src="{% static 'js/topic-edit.js' %}"></script>
{% endblock %}

templates/redirect.html
{% extends 'base.html' %}


{% block content %}

<p> Loading... </p>
{% endblock %}

templates/topic_form.html
{% extends 'base.html' %}
{% block content %}

     <form method="post">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit" class="btn btn-primary" name = 'submit'> Submit </button>
     </form>

     <script>
          document.querySelector('form').classList.add('submit-form')
     </script>

{% endblock %}