verbal/urls.py
from django.contrib import admin
from django.urls import path
import flash.views as f

urlpatterns = [
    path('', f.welcome, name = 'welcome'),
    path('<int:topic_id>/', f.home_view, name = 'topic-page'),
    path('loading/', f.redirect_view, name = 'loading'),
    path('create-topic/', f.create_topic, name='create-topic'),
    path('create-topic/<str:tag>/', f.create_topic, name='create-topic-for-tag'),
    path('edit-topic', f.edit_topic, name='edit-topic'),
    path('delete-topic/', f.delete_topic, name='delete-topic'),
    path('create-tag/', f.create_tag, name='create-tag'),
    path('remove-tag/', f.remove_tag, name='remove-tag'),
    path('topic/<int:topic_id>/add_use_case/', f.add_use_case, name='add_use_case'),
    path('edit-use-case/', f.edit_use_case, name='edit-use-case'),
    path('delete-use-case/', f.delete_use_case, name='delete-use-case'),
    path('topic/<int:topic_id>/add_comparison/', f.add_comparison, name='add_comparison'),
    path('comparison/<int:comparison_id>/comparison-rows/', f.comparison_datatable, name='comparisons-data'),
    path('comparison/<int:comparison_id>/edit-comparison/', f.edit_comparison, name='edit-comparison'),
    path('delete-comp/', f.delete_comparison, name='delete-comparison'),
    path('admin/', admin.site.urls),
]

flash/models.py
from django.db import models

class Topic(models.Model):
    topic = models.CharField(max_length=200, null=False, blank=False)
    description = models.TextField(max_length=400, null=True, blank=True)

    def serialize(self):
        return {
            'id': self.id,
            'topic': self.topic,
            'description': self.description,
        }

class UseCase(models.Model):
    topic = models.ForeignKey(Topic, related_name='use_cases', on_delete=models.CASCADE)
    description = models.TextField()

class Comparison(models.Model):
    topic = models.ForeignKey(Topic, related_name='comparisons', on_delete=models.CASCADE)
    comparison1 = models.CharField(max_length=255, null=True, blank=True)
    comparison2 = models.CharField(max_length=255, null=True, blank=True)
    
class ComparisonRow(models.Model):
    comparison = models.ForeignKey(Comparison, related_name='comparison_rows', on_delete=models.CASCADE)
    keyword = models.CharField(max_length=200)
    row1 = models.TextField()
    row2 = models.TextField()
    
class Tag(models.Model):
    topic = models.ManyToManyField(Topic)
    tag = models.CharField(max_length=200)

class Note(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='notes')
    content = models.TextField()

templates/comparisons/add_comparison.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
     <button type="button" class="btn btn-primary mb-2 mt-2" id="add_comp_row"> Add Row </button>
     <form method="post">
          {% csrf_token %}
          <table class="table  table-dark table-striped">
               <thead>
                    <tr>
                         <th><input class="form-control" list="datalistOptions" required id="id_comparison1" name="comparison1" placeholder="Heading 1"/></th>
                         <th><input class="form-control" list="datalistOptions" required id="id_comparison2" name="comparison2" placeholder="Heading 2"/></th>
                         <th style="width:10%">Exclude Row</th>
                    </tr>
               </thead>
               <tbody>   
                    
               </tbody>
        </table>
                   
        <button type="submit" class="btn btn-success">Add</button>
        {{ child_formset.management_form }}
     </form>

     <datalist id="datalistOptions">
          {% for option in options %}
               <option value="{{option}}">
          {% endfor %}
     </datalist>
</div>
{% endblock %}

{% block javascript %}
     <script src="{% static 'js/comparison.js' %}"></script>
{% endblock %}

templates/comparisons/comparisons.html
{% load static %}

<div class="all_comparisons">
     {% csrf_token %}
     {% for comparison in comparisons %}
          <div class="table-responsive">
               <input type="hidden" id="cmp-id" value="{{comparison.id}}"/>
               <input type="hidden" id="cmp-url" value="{% url 'edit-comparison' comparison_id=comparison.id %}"/>
               <table class="comp table table-dark table-striped m5" data-url="{% url 'comparisons-data' comparison_id=comparison.id %}"> 
                    <thead>
                         <tr>
                              <th>{{comparison.comparison1}}</th>
                              <th>{{comparison.comparison2}}</th>
                         </tr>
                    </thead>
                    <tbody></tbody>
               </table>
          </div>
          <hr>
     {%endfor%}
 </div>

{% block javascript %}
<script src="{% static 'js/comparison.js' %}"></script>
{% endblock %}

templates/comparisons/edit_comparison.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
     <button type="button" class="btn btn-primary mb-2 mt-2" id="add_comp_row"> Add Row </button>
     <form method="post">
          {% csrf_token %}
          <table class="table table-dark table-striped">
               <thead>
                    <tr>
                         <th>{{comparison.comparison1}}</th>
                         <th>{{comparison.comparison1}}</th>
                         <th style="width:10%">Exclude Row</th>
                    </tr>
               </thead>
               <tbody>   
                    
               </tbody>
          </table>
          {% for form in child_formset %}
               <div class="temp_comp_row" display="style:hidden">
                    {{ form.as_p }}
               </div>
          {% endfor %}
        <button type="submit" class="btn btn-success">Add</button>
        {{ child_formset.management_form }}
     </form>
</div>
{% endblock %}

{% block javascript %}
     <script src="{% static 'js/comparison.js' %}"></script>
{% endblock %}

templates/comparisons/edit_comparisons.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
     <button type="button" class="btn btn-primary mb-2 mt-2" id="add_comp_row"> Add Row </button>
     <form method="post">
          {% csrf_token %}
          <table class="table table-dark table-striped">
               <thead>
                    <tr>
                         <th><input class="form-control" list="datalistOptions" required id="id_comparison1" name="comparison1" placeholder="Heading 1"/></th>
                         <th><input class="form-control" list="datalistOptions" required id="id_comparison2" name="comparison2" placeholder="Heading 2"/></th>
                         <th style="width:10%">Exclude Row</th>
                    </tr>
               </thead>
               <tbody>   
                    
               </tbody>
        </table>
                      
        

      
        
        <p>
          
          
        </p>
                   
        <button type="submit" class="btn btn-success">Add</button>
        {{ child_formset.management_form }}
     </form>

     <datalist id="datalistOptions">
          {% for option in options %}
               <option value="{{option}}">
          {% endfor %}
     </datalist>
</div>
{% endblock %}

{% block javascript %}
     <script src="{% static 'js/comparison.js' %}"></script>
{% endblock %}